source:
  host: 127.0.0.1
  port: 1433
  username: sa
  password: Test1234!

target:
  host: 127.0.0.1
  port: 4000
  username: root
  password: ""

convert:
  schemas:
  tables:
  drop-if-exists: false
  continue-on-error: true

spring:
  main:
    banner-mode: off
logging:
  level:
    root: OFF
    com.tool: OFF
